In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/HHS_Unaccompanied_Alien_Children_Program.csv")
print(df.shape)
df.head()

(1170, 6)

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
0,"December 21, 2025",6.0,18.0,11.0,"2,484",14.0
1,"December 18, 2025",11.0,50.0,6.0,"2,472",16.0
2,"December 17, 2025",7.0,31.0,11.0,"2,481",10.0
3,"December 16, 2025",8.0,54.0,15.0,"2,468",9.0
4,"December 15, 2025",11.0,42.0,9.0,"2,470",7.0

In [3]:
df.info()
df.isna().sum()
df.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1170 entries, 0 to 1169
Data columns (total 6 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Date                                             720 non-null    object
 1   Children apprehended and placed in CBP custody*  720 non-null    float64
 2   Children in CBP custody                          720 non-null    float64
 3   Children transferred out of CBP custody          720 non-null    float64
 4   Children in HHS Care                             720 non-null    object
 5   Children discharged from HHS Care                720 non-null    float64
dtypes: float64(4), object(2)
memory usage: 55.0+ KB

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
1165,NaN,NaN,NaN,NaN,NaN,NaN
1166,NaN,NaN,NaN,NaN,NaN,NaN
1167,NaN,NaN,NaN,NaN,NaN,NaN
1168,NaN,NaN,NaN,NaN,NaN,NaN
1169,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.columns = [
    "date",
    "apprehended",
    "cbp_custody",
    "cbp_transferred",
    "hhs_care",
    "hhs_discharged",
]

df.head()

,date,apprehended,cbp_custody,cbp_transferred,hhs_care,hhs_discharged
0,"December 21, 2025",6.0,18.0,11.0,"2,484",14.0
1,"December 18, 2025",11.0,50.0,6.0,"2,472",16.0
2,"December 17, 2025",7.0,31.0,11.0,"2,481",10.0
3,"December 16, 2025",8.0,54.0,15.0,"2,468",9.0
4,"December 15, 2025",11.0,42.0,9.0,"2,470",7.0

In [6]:
df = df.dropna(how="all").copy()
print(df.shape)   # should be (720, 6)

(720, 6)

In [7]:
df["hhs_care"] = df["hhs_care"].str.replace(",", "").astype(int)
df.dtypes

date                object
apprehended        float64
cbp_custody        float64
cbp_transferred    float64
hhs_care             int64
hhs_discharged     float64
dtype: object

In [8]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
apprehended,720.0,93.523611,72.646625,0.0,12.00,99.0,147.25,333.0
cbp_custody,720.0,171.494444,126.354965,7.0,36.00,193.0,263.25,531.0
cbp_transferred,720.0,128.668056,97.322012,0.0,14.00,157.0,199.25,440.0
hhs_care,720.0,6061.275000,2833.070109,1972.0,2467.75,6406.5,8010.25,11516.0
hhs_discharged,720.0,173.406944,125.702841,0.0,19.75,181.0,267.00,505.0

In [12]:
df[["cbp_custody", "hhs_care"]].agg(["min", "median", "mean", "max"])

        cbp_custody   hhs_care
min        7.000000   1972.000
median   193.000000   6406.500
mean     171.494444   6061.275
max      531.000000  11516.000